name: dart_2
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  dcdg: ^4.1.0

dependency_overrides:
  analyzer: ^3.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
